name: client
description: "cinemax"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.4.0
  email_auth: ^1.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  intl: ^0.19.0
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  smooth_page_indicator: ^1.1.0
  ui_kit:
    path: ../ui_kit
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
